version: "4.27"

services:
  backend:
    build: .
    container_name: todo_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KET=test
      - DEBUG=True
