name: Django Todo Project Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Compose
      run: docker-compose up -d
    -name: Run Tests
      run: docker exec backend sh -c "flake8 && pytest ."
