name: Django Todo Project Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Compose
      run: docker-compose up -d
    - name: Run Tests
      run: docker exec todo_backend sh -c "flake8 && pytest ."

  Deploy:
    name: Deploy
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Connect and Execute Commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        script: ls

